name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pages: write
      id-token: write

    concurrency:
      group: pages

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Persist npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

      - name: Persist Eleventy .cache
        uses: actions/cache@v3
        with:
          path: ./.cache
          key: ${{ runner.os }}-eleventy-fetch-cache

      - run: npm ci
      - run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
